spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://${DB_URL_TEST:localhost:5432/erp-demo-test}
    username: ${DB_USERNAME_TEST:test}
    password: ${DB_PASSWORD_TEST:test}
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        cache:
          use_second_level_cache: false
          use_query_cache: true
          region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
      javax:
        cache:
          provider: org.hibernate.cache.jcache.JCacheRegionFactory
          uri: classpath:hazelcast.xml

jwt:
  accessToken:
    expirationMs: 86400000